### ISSUE TITLE
partial sweeps or completed sweeps

### ISSUE THREAD

**Issue by Yiguan** [CshlSiepelLab/arg-selection#3]
Hi,

Just wondering if SIA is just detect partial sweeps?

More specifically, does a focal site have to be a polymorphic site, or fixed site(substitute with derived AF=1, completed sweeps)? I looked at the paper and it seems to only use polymophic sites. I am not sure if my understading is right.

Thanks in advance!

Yiguan

**Comment by ziyimo** [comment]
Hi Yiguan,

Thanks for reaching out!
You are right that in the manuscript we only benchmarked the method and applied it to polymorphic sites. The training data consisted only of partial sweeps. But SIA can certainly be applied to infer sweeps completed in a population. All you need to do is to simulate a bunch of complete sweeps to train the model.

Best,
Mo

**Comment by Yiguan** [comment]
Thanks for your reply! I am really interested in SIA and trying some simulations on my data. 
However, I noticed that you used `discoal` to do the simulation in the MBE paper. But in this Github code, you seemed to use SLiM. I am wondering which one you prefer to use? and have you run both and compared them?

Thanks,
Yiguan

**Comment by ziyimo** [comment]
Sorry, this slipped under my radar. We indeed used `discoal` for all of our simulations due to computational and time constraints. We included only recipes for SLiM simulation scripts in the repo because discoal has a very straightforward command line interface that is explained well in their documentation.

As for the choice between the two, it really depends on your use case:

* `discoal` is definitely much faster and provides you with a large amount of data to train a deep learning model. It can simulate many demographic scenarios (multiple populations, migration etc.) and single selective sweeps. So depending on the population you're working on, if you have a simple case, `discoal` can have enough features for your simulation. There are some limitations to `discoal`, for example, migration is not allowed simultaneously with selection (at least this is the case last time I checked the documentation).
* You can pretty much do anything with `SLiM`. So if you have a very complex demographic model and want to simulate it accurately, you probably want to use `SLiM`. It is definitely much slower than `discoal` (even with tricks like tree-sequence recording and recapitation), but to speed up the simulations you do have the choice to scale down the population size/generations.

**Comment by Yiguan** [comment]
Great, thanks so much!
